version: '3.1'

services:
  db:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    expose:
      - 5432
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "psql", "-U", "thesismanager", "-d", "thesismanagement", "-c", "SELECT * FROM student, teacher LIMIT 1"]
      interval: 10s
      timeout: 30s
      retries: 5
  authsources:
    build:
      context: ./saml
      dockerfile: ./Dockerfile
    volumes:
      - saml_config:/var/www/simplesamlphp/config:rw
    depends_on:
      db:
        condition: service_healthy
  saml:
    image: kenchan0130/simplesamlphp
    depends_on:
      - authsources
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: thesismanagement-saml
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://server:3001/login/callback
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://server:3001/logout/callback
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - saml_config:/var/www/simplesamlphp/config:ro
  server:
    image: node:21.1
    environment:
      - DOCKER_SETUP=true
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npm install && node index.js"
    expose:
      - 3001
    ports:
      - 3001:3001
  frontend:
    image: node:21.1
    environment:
      - DOCKER_SETUP=true
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - server
    command: >
      sh -c "npm install && npm run docker"
    expose:
      - 5173
    ports:
      - 5173:5173
volumes:
  saml_config: