version: '3.1'

services:
  db:
    build:
      context: ../database
      dockerfile: ./Dockerfile
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    expose:
      - 5432
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "psql", "-U", "thesismanager", "-d", "thesismanagement", "-c", "SELECT * FROM student, teacher LIMIT 1"]
      interval: 10s
      timeout: 30s
      retries: 5
  saml:
    build:
      context: ../saml
      dockerfile: ./Dockerfile
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: thesismanagement-saml
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:3001/api/saml/login/callback
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:3001/api/saml/logout/callback
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8080
    ports:
      - 8080:8080