INSERT INTO public.thesis_request(student_id, proposal_id, title, description, supervisor, co_supervisor, apply_date, status_clerk, status_teacher, approval_date)
VALUES(1,2, 
 'Progettazione e sviluppo di un cluster di  mini radio sonde per misure Lagrangiane delle fluttuazioni di quantità fisiche in atmosfera',
 'Lattività di ricerca prevede la progettazione di una mini radio sonda innovativa per la misura delle fluttuazioni di temperatura pressione e umidità’ entro le nuvole tiepide. Il tesista dovrà prestare particolare attenzione alla minimizzazione di pesi ed ingombri del PCB.
Sarà necessario inoltre lo sviluppo del firmware associato.  Il firmware sarà sviluppato in collaborazione con il team di ricerca del progetto MIGRE. Particolare attenzione dovrà esser posta sulla massimizzazione della durata della batteria della sonda; pertanto, il firwmare dovrà essere sviluppato in accordo con il paradigma "low-power" e dovrà essere in grado di gestire il microcontrollore in tal senso.', 
 'gianalessandropasero.eros@polito.it', 
 ARRAY['randazzo.vincenzo@polito.it','tordella.daniela@polito.it']::text[],
 '2023-09-19', 
 true,
 true,
 '2023-10-8'),
 (2,3, 
 'Analysis and Correlation of Behaviour on Online Social Networks',
 'Online social networks, such as Instagram and Facebook, allow users to interact and debate with each other. In this research, the candidate will collect large quantities of data from social networks and from public repositories such as Wikidata. The data will be organized and analyzed using big data techniques (such as Pyspark). Then, the student will characterize the behaviour of different classes of users on the social network (e.g., nationality, activity,  language, age, etc.). The student will analyze possible bias in the categories and the dynamic of the changes. The student will possibly use machine learning techniques, forecasting methods and graphs.', 
 'trevisan.martino@polito.it', 
 ARRAY['vassio.luca@polito.it']::text[],
 '2023-11-22', 
 true,
 false,
 null),
(3,4, 
 'L’analisi del fabbisogno di energia elettrica e termica del parco edilizio esistente attraverso un sistema informativo geografico',
 'Questo lavoro parte da un analisi delle banche dati esistenti sulle caratteristiche del parco edilizio della Città di Torino con una correzione informatizzata dei dati, principalmente geometrici. Alcuni dati sono relativi al singolo edificio, altri, invece, si riferiscono alle sezioni di censimento, altri ancora vengono ricavati indirettamente dai dati esistenti. Vengono descritti i modelli di riferimento per il calcolo del fabbisogno termico ed elettrico che poi si applicano per poter effettuare delle valutazioni sul risparmio energetico sugli edifici. L’obiettivo di questo lavoro è quello di realizzare una procedura che possa poi essere estesa su tutto il territorio provinciale con un livello di approssimazione che dipende dalla disponibilità e qualità dei dati di partenza. Il software di georeferenziazione open source non verrà utilizzato solo per rappresentare dei dati ma anche per elaborare nuove informazioni, su cui poter condurre anche analisi statistiche. Ciò consentirà di poter valutare l’impatto delle politiche di risparmio energetico sul territorio.', 
 'mutani.guglielmina@polito.it', 
 ARRAY[]::text[],
 '2023-07-19', 
 false,
 false,
 null),
 (5,5, 
 'Flow control for laminar/transitional flows',
 'see attachment.', 
 'serpieri.jacopo@polito.it', 
 ARRAY[]::text[],
 '2023-12-1', 
 null,
 null,
 null),
 (6,8, 
 'Well being app',
 'Obbiettivo della tesi è sviluppare una app e relativo back end per supportare le persone a perseguire uno stile di vita salutare. 
La app raccoglie (direttamente, o tramite device esterni tipo smartwatch o fitbit) dati sulla vita della persona (attività fisica, qualità e durata del sonno, pressione, pulsazioni) (nutrizione, tipo e quantità del cibo mangiato e delle bevande). Confrontando i dati raccolti con pattern predefiniti e possibilmente con analisi mediche supplettive  la app suggerisce  modifiche allo stile di vita (recommendation). Via via che la persona viene monitorata altre modifiche sono suggerite e il loro effetto verificato.
La parte back end della app raccoglie in modo anonimo i dati di molti utenti e utilizzando tecniche statistiche e di machine learning costruisce e raffina modelli e pattern predittivi da usare per le recommendation.
 Le recommendation iniziali sono derivate dalla letteratura scientifica su aging e well being (vedere ad esempio Fontana L., The path to longevity).  Scopo di lungo termine della app è di raccogliere dati per validare e migliorare le recommendation.
 Il lavoro è svolto in collaborazione con University of Sydney e Azienda Ospedaliera Verona. Il lavoro supporta una tesi lato app e una lato backend.', 
 'morisio.maurizio@polito.it', 
 ARRAY[]::text[],
 '2023-10-10', 
 true,
 null,
 null),
 (36,18, 
 'Analisi della siccità in Piemonte',
 'Analisi della siccità in Piemonte', 
 'revelli.roberto@polito.it', 
 ARRAY['viglione.alberto@polito.it']::text[],
 '2023-11-10', 
 false,
 true,
 null),
 (98,32, 
 'Malicious Code Detection for Automotive-secured systems',
 'The recent period is growing the number of attacks that leverage on relaying third parties’ software exploits. Many security vulnerability detection tools are already available today in the market. These tools allow scanning of the source code of projects, infrastructure and applications and reporting potential security vulnerabilities and weaknesses. The current approach swing between two categories of analyzers: dynamic and static. Both are not useful when the third-party software module is delivered to the customer directly compiled code without source code sharing. This habit is quite common in the automotive domain for protecting Intellectual Properties (IP), made easy by AUTOSAR Architecture Framework that guarantees software module compatibility.
In the present thesis, the student shall develop a novel static analysis based on traditional and deep-learning methods that detect potential software vulnerabilities on binary code instead of traditional source code.', 
 'dicarlo.stefano@polito.it', 
 ARRAY['savino.alessandro@polito.it,']::text[],
 '2023-06-21', 
 true,
 true,
'2023-07-16');
